### ISSUE TITLE
[Visual] Large Text Visualization in a Habit

### ISSUE THREAD

**Issue by FranprzDev** [thestonechat/habits-sh#2]
### **Summary**
<hr>

When you add a large text to add an habit, the previsualization of a habit is broken.

### **Steps To Reproduce**
<hr>

1.  Go to the page
2. Click the add habit button
3. Add an large text
4. Click the create button

Image:
![image](https://github.com/user-attachments/assets/53547fcd-5aaf-4d2b-9ffb-2e13e726e0e9)

**Comment by thestonechat** [comment]
fixed!

**Comment by FranprzDev** [comment]
Thanks!
